version: 2

run:
  timeout: 1m
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/
    - test/

linters:
  disable-all: true
  enable:
    - asciicheck
    - depguard
    - dogsled
    - errcheck
    - exhaustive
    - gocognit
    - gocyclo
    - goheader
    - gomodguard
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
    - whitespace
    - durationcheck
    - forbidigo
    - forcetypeassert
    - importas
    - nilerr
    - predeclared
    - thelper
    - tparallel
    - wastedassign
    - promlinter
    - bodyclose
    # - dupl
    - godot
    - funlen
    - wsl
    # - gochecknoglobals
    # - gochecknoinits
    - goconst
    - gocritic
    # - godox
    # - goerr113
    # - gosec
    # - noctx
    - prealloc
    # - stylecheck
    # - testpackage
    # - cyclop
    # - errorlint
    - nlreturn
    # - revive
    # - tagliatelle
    - unparam

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 3
  depguard:
    rules:
      main:
        files:
          - "**/*.go"
        allow:
          - webApp/domain
          - webApp/internal/repository
          - webApp/internal/server
          - webApp/internal/service
          - webApp/internal/service/mocks
          - webApp/internal/transport/handlers
          - webApp/pkg/logger
          - github.com/gin-gonic/gin
          - github.com/spf13/viper
          - github.com/shopspring/decimal
          - github.com/joho/godotenv
          - github.com/kelseyhightower/envconfig
          - github.com/lib/pq
          - github.com/sirupsen/logrus
          - github.com/DATA-DOG/go-sqlmock
          - github.com/stretchr/testify/assert
          - github.com/golang/mock/gomock
          - github.com/spf13/viper
          - github.com/gin-gonic/gin
          - github.com/shopspring/decimal
          - github.com/joho/godotenv
          - github.com/kelseyhightower/envconfig
          - github.com/lib/pq
          - github.com/sirupsen/logrus
          - github.com/DATA-DOG/go-sqlmock
          - github.com/stretchr/testify/assert
          - github.com/golang/mock/gomock

issues:
  exclude-rules:
    - path: (_test\.go|tests)
      linters:
        - bodyclose
        - dupl
        - funlen
        - goerr113
        #- gosec
        - noctx
    - path: (internal/delivery/http)
      linters:
        - godot
    - path: _test\.go
      linters:
        - errcheck