services:
  web-app:
    build: ./
    command: ./webApp
    ports:
      - 8085:8085
    depends_on:
      - db
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    networks:
      - webappcsv_network1
  db:
    image: postgres:15
    restart: always
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_DBNAME=${DB_DBNAME}
    volumes:
      - ./.database/init:/docker-entrypoint-initdb.d
      - ./.database/data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - webappcsv_network1

networks:
  webappcsv_network1:
    external: true
    name: webappcsv_network1