// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/proto.proto

//import "google/protobuf/timestamp.proto"; //RFC3339

package grpcPb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SortService_Fetch_FullMethodName = "/grpcPb.SortService/Fetch"
	SortService_List_FullMethodName  = "/grpcPb.SortService/List"
)

// SortServiceClient is the client API for SortService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SortServiceClient interface {
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FethResponce, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponce, error)
}

type sortServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSortServiceClient(cc grpc.ClientConnInterface) SortServiceClient {
	return &sortServiceClient{cc}
}

func (c *sortServiceClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FethResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FethResponce)
	err := c.cc.Invoke(ctx, SortService_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sortServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponce, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponce)
	err := c.cc.Invoke(ctx, SortService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SortServiceServer is the server API for SortService service.
// All implementations must embed UnimplementedSortServiceServer
// for forward compatibility.
type SortServiceServer interface {
	Fetch(context.Context, *FetchRequest) (*FethResponce, error)
	List(context.Context, *ListRequest) (*ListResponce, error)
	mustEmbedUnimplementedSortServiceServer()
}

// UnimplementedSortServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSortServiceServer struct{}

func (UnimplementedSortServiceServer) Fetch(context.Context, *FetchRequest) (*FethResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedSortServiceServer) List(context.Context, *ListRequest) (*ListResponce, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedSortServiceServer) mustEmbedUnimplementedSortServiceServer() {}
func (UnimplementedSortServiceServer) testEmbeddedByValue()                     {}

// UnsafeSortServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SortServiceServer will
// result in compilation errors.
type UnsafeSortServiceServer interface {
	mustEmbedUnimplementedSortServiceServer()
}

func RegisterSortServiceServer(s grpc.ServiceRegistrar, srv SortServiceServer) {
	// If the following call pancis, it indicates UnimplementedSortServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SortService_ServiceDesc, srv)
}

func _SortService_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortServiceServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortService_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortServiceServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SortService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SortServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SortService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SortServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SortService_ServiceDesc is the grpc.ServiceDesc for SortService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SortService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcPb.SortService",
	HandlerType: (*SortServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _SortService_Fetch_Handler,
		},
		{
			MethodName: "List",
			Handler:    _SortService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/proto.proto",
}
